version: '3.3'

services:
    #AAI Resources
    aai-resources:
        depends_on:
            - aai-cassandra
        image: onap/aai-resources:1.6.6
        container_name: aai-resources
        ports:
            - "8447:8447"
        volumes: 
            - ./aai_oxm_v19.xml:/opt/app/aai-resources/resources/schema/onap/oxm/v19/aai_oxm_v19.xml
            - ./DbEdgeRules_v19.json:/opt/app/aai-resources/resources/schema/onap/dbedgerules/v19/
            - ./janusgraph-realtime.properties:/opt/app/aai-resources/resources/etc/appprops/janusgraph-realtime.properties
            - ./janusgraph-cached.properties:/opt/app/aai-resources/resources/etc/appprops/janusgraph-cached.properties
        networks:
            - storage_network    

    #Cassandra
    aai-cassandra:
        image: cassandra:3.11
        container_name: aai-cassandra
        environment:
            #HEAP_NEWSIZE: 1M
            #MAX_HEAP_SIZE: 1024M
            - "CASSANDRA_START_RPC=true"
        ports:
            - "9042:9042"
            - "9160:9160"
        volumes:
            -  ~/AAI_FILES/STORAGE_SPACE:/var/lib/cassandra
        networks:
            - storage_network
 

networks: 
    storage_network:
        driver: bridge


